export interface SystemMetadata {
  systemTables: Set<string>;
  defaultFormColumns: Set<string>;
  preferredForeignKeySuffixes: string[];
  systemTableAllowedForeignKeys: Set<string>;
}

const SYSTEM_TABLES = [
  "FileToken",
  "Language",
  "SLAWorkFlowState",
  "File",
  "SLAFolderTree",
  "Alert",
  "AccountFilter",
  "SLACriteria",
  "GroupFolderTree",
  "Email",
  "Account",
  "Directory",
  "GroupFolderTreePermission",
  "DirectoryFile",
  "EmailFile",
  "AccountPermissionStaticComputed",
  "AccountFolderTree",
  "ResourceBuilder",
  "__EFMigrationsHistory",
  "PushNotification",
  "AccountFolderTreePermission",
  "AspNetRoles",
  "AspNetUsers",
  "AspNetRoleClaims",
  "SyncMigration",
  "AspNetUserClaims",
  "CommunicationOtherEmail",
  "GoogleToken",
  "AccountComputedPermissionComputed",
  "AspNetUserLogins",
  "ShareFile",
  "ReceivedEmail",
  "AppStatus",
  "AspNetUserRoles",
  "ShareFileFile",
  "AccountHierarchy",
  "AspNetUserTokens",
  "FormReceivedEmail",
  "MultiSelect",
  "SMS",
  "AccountClaim",
  "FormFolderTree",
  "Permission",
  "SLANotification",
  "SMSAttribute",
  "Role",
  "NotificationSettingGroup",
  "FileMark",
  "__DBUpMigrationsHistory",
  "NotificationSettingIdent",
  "Favorite",
  "FilePermission",
  "GroupNotificationSetting",
  "AuditLog",
  "SLANotificationWorkFlowState",
  "Folder",
  "AccountNotificationSetting",
  "CommunicationFile",
  "ResultList",
  "XMLDefinition",
  "EventLog",
  "SystemDataRefresh",
  "CourseState",
  "EmailAttribute",
  "AccountColumnSetting",
  "AccountExportColumnSetting",
  "SegmentType",
  "SLAProcess",
  "ResultListData",
  "FileTimestamp",
  "Connect",
  "AlertSetting",
  "Device",
  "Note",
  "FileWebDav",
  "Report",
  "FolderTree",
  "History",
  "SLANotificationSend",
  "ToDoList",
  "ReportColumn",
  "CommunicationType",
  "ReportFilter",
  "Icon",
  "HistoryData",
  "CommunicationPriority",
  "Communication",
  "Time",
  "CommunicationPermission",
  "Group",
  "HistoryType",
  "SLA",
  "CultureInfoType",
  "GroupAccount",
  "TaskScheduler",
  "SLADay",
  "GroupRole",
  "Resource"
];
const DEFAULT_FORM_COLUMNS = ["ID", "AccountID", "CreateDate", "LastUpdate", "LastUpdateAccountID", "State"];
const DEFAULT_PREFERRED_SUFFIXES = ["ID", "Ident", "Guid"];
const DEFAULT_SYSTEM_TABLE_ALLOWED_FKS = ["ID", "Ident"];

const STATIC_METADATA: SystemMetadata = {
  systemTables: new Set(SYSTEM_TABLES),
  defaultFormColumns: new Set(DEFAULT_FORM_COLUMNS),
  preferredForeignKeySuffixes: DEFAULT_PREFERRED_SUFFIXES,
  systemTableAllowedForeignKeys: new Set(DEFAULT_SYSTEM_TABLE_ALLOWED_FKS)
};

export function getSystemMetadata(): SystemMetadata {
  return STATIC_METADATA;
}
